on:
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    env:
      SEND_EMAIL: ${{ vars.SEND_EMAIL }}
      SEND_EMAIL_PASSWORD: ${{ secrets.SEND_EMAIL_PASSWORD }}
      SETTINGS: ${{ vars.SETTINGS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: 安装依赖环境
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 获取yaml文件名
        id: get_variables
        run: |
          WORKFLOW_PATH="${{ github.workflow }}"
          WORKFLOW_NAME=$(basename $WORKFLOW_PATH)
          WORKFLOW_NAME=${WORKFLOW_NAME/\.yml/}
          WORKFLOW_NAME=${WORKFLOW_NAME/.*/}
          WORKFLOW_NAME=${WORKFLOW_NAME^^}
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_OUTPUT

      - name: 运行python脚本
        id: python_scripts
        run: |
          if [ -z "${{ vars.SETTINGS }}" ]; then
            echo "没有配置参数，不执行脚本"
          else
            python src/main_tiktok.py ${{ steps.get_variables.outputs.WORKFLOW_NAME }}
          fi